### ISSUE TITLE
load_callback and $data 

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [hofff/contao-selectri#11]
hi :)
Könnte man in die Verarbeitung der DCA-Daten eine Möglichkeit integrieren, das mir kein Fehler angezeigt wird, wenn ich $data noch nicht gesetzt habe?

In meinem Fall setze ich die $data->getConfig()->setTreeConditionExpr('type = \'regular\' AND tstamp > 0'); während eines load_callbacks. Da ich darin keinen Zugriff auf das bereits ausgelöste $data-objekt habe, muss ich darin die $data-function komplett neu aufrufen.

Oder seh' ich da eine andere Möglichkeit nur noch nicht??

**Comment by backbone87** [comment]
das problem scheint gelöst zu sein?

**Comment by MoniqueHahnefeld** [comment]
ich teste das demnächst und melde mich nochmal. bin bisher nicht dazu gekommen...

**Comment by backbone87** [comment]
da hier leider keine antwort mehr gekommen ist -> close
