### ISSUE TITLE
collectFormData in selectri.js verursacht probleme mit array-artigen input-namen

### ISSUE THREAD

**Issue by backbone87** [hofff/contao-selectri#12]
https://github.com/backbone87/contao-selectri/blob/2.x/TL_ROOT/system/modules/backboneit_selectri/html/js/selectri.js#L410

**Comment by MoniqueHahnefeld** [comment]
Was meinst du mit "array-artigen input-namen" :)? Bsp.??

**Comment by backbone87** [comment]
fixed in 4.0.0-rc2
