### ISSUE TITLE
Sortierung der ausgewählten Elemente nicht möglich

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-selectri#14]
Wenn man z.B. mit dem CE "Inhaltsreferenzen" (hofff/contao-content) mehrere Elemente aus der Liste ausgewählt hat, so kann man sie nach dem Auswählen nicht mehr sortieren. Leider gibt es keinen JS-Fehler in der Konsole.

**Comment by backbone87** [comment]
fixed in 3d75f199fe86c1a5eb20ed297c4e3f94eaf5830e
